
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './redux/provider'
import Navbar from '@/components/Navbar'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='max-w-4xl mx-auto p-4'>
        <Providers>
          <Navbar />
          {children}
        </Providers>
        </div>
      </body>
    </html>
  )
}
